name: Workflow1
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Msg
        run: echo 'echoing the message'

      - name: CheckoutTask
        uses: actions/checkout@v7.0.0

      - name: List files
        run: ls -la

      - name: Generate ASCII ART
        run: |
             sudo apt-get update && sudo apt-get install figlet -y
    
  
